Name:           waltz
Version:        14.4
Release:        1
Summary:        waltz backup tool
License:        Public Domain
Group:          Admin
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch

Requires:       perl(Carp) >= 1
Requires:       perl(Config::Nested) >= 1
Requires:       perl(Cwd) >= 1
Requires:       perl(Data::Dumper) >= 1
Requires:       perl(File::Spec) >= 1
Requires:       perl(IO::Scalar) >= 1
Requires:       perl(IO::Tee) >= 0.64
Requires:       perl(Mail::Send) >= 1
Requires:       perl(Pod::Usage) >= 1
Requires:       perl(Text::Table) >= 1
Requires:       perl(Tie::IxHash) >= 1

Requires:       logrotate
Requires:       crontabs

Source: %{name}-%{version}-%{release}.tgz

%description
waltz creates and manages a directory of linked backups of remote and
local systems under a common repository.

%prep
%setup -q
pwd

%build

%install
rm -rf $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{_sbindir}/*
%{_sysconfdir}/cron.daily/00waltz.cron
%{_sysconfdir}/logrotate.d/waltz.logrotate
%{_sysconfdir}/%{name}.d
%{_datarootdir}/%{name}/*
%{_mandir}/man8/*

%changelog
* Wed Aug 06 2014 Anthony Fletcher <arif@bifb.org> 13.12-1
- Specfile autogenerated by cpanspec 1.78.

